/**
 * Pure TypeScript PDF invoice generator.
 * No external dependencies. Produces valid PDF-1.4.
 * Designed for InvoiceForge professional invoices.
 */

import { Business, Job, LineItem } from "./types";

function escapePdf(str: string): string {
  return str
    .replace(/\\/g, "\\\\")
    .replace(/\(/g, "\\(")
    .replace(/\)/g, "\\)")
    .replace(/\r/g, "")
    .replace(/\n/g, " ");
}

function formatRand(amount: number): string {
  return "R " + amount.toLocaleString("en-ZA", {
    minimumFractionDigits: 2,
    maximumFractionDigits: 2,
  });
}

function buildContentStream(
  business: Business,
  job: Job,
  invoiceNumber: string
): string {
  const lines: string[] = [];
  let y = 780;

  const add = (text: string, x: number, size = 11, bold = false) => {
    const font = bold ? "F2" : "F1";
    lines.push(`BT /${font} ${size} Tf ${x} ${y} Td (${escapePdf(text)}) Tj ET`);
  };

  const addRight = (text: string, x: number, size = 11, bold = false) => {
    const font = bold ? "F2" : "F1";
    const approxWidth = text.length * (size * 0.5);
    lines.push(`BT /${font} ${size} Tf ${x - approxWidth} ${y} Td (${escapePdf(text)}) Tj ET`);
  };

  // Header
  add(business.name, 50, 18, true);
  y -= 18;
  if (business.phone) {
    add(business.phone, 50, 9);
    y -= 12;
  }
  if (business.email) {
    add(business.email, 50, 9);
    y -= 12;
  }
  if (business.address) {
    add(business.address, 50, 9);
    y -= 12;
  }
  if (business.isVatRegistered && business.vatNumber) {
    add(`VAT: ${business.vatNumber}`, 50, 9);
    y -= 12;
  }

  y = 780;
  addRight("INVOICE", 545, 20, true);
  y -= 20;
  addRight(invoiceNumber, 545, 12, true);
  y -= 14;
  const invDate = job.sentAt
    ? new Date(job.sentAt).toLocaleDateString("en-ZA")
    : new Date().toLocaleDateString("en-ZA");
  addRight(`Date: ${invDate}`, 545, 10);
  y -= 12;
  if (job.dueDate) {
    addRight(`Due: ${new Date(job.dueDate).toLocaleDateString("en-ZA")}`, 545, 10);
  }

  // Separator
  y = 700;
  lines.push(`0.7 w 50 ${y} m 545 ${y} l S`);
  y -= 25;

  // Bill To
  add("BILL TO", 50, 9, true);
  y -= 14;
  add(job.customer.name || "Customer", 50, 12, true);
  y -= 14;
  if (job.customer.address) {
    add(job.customer.address, 50, 10);
    y -= 12;
  }
  if (job.customer.phone) {
    add(job.customer.phone, 50, 10);
    y -= 12;
  }
  if (job.customer.email) {
    add(job.customer.email, 50, 10);
    y -= 12;
  }

  y -= 10;
  if (job.notes || job.rawInput) {
    add("JOB DESCRIPTION", 50, 9, true);
    y -= 14;
    const desc = (job.notes || job.rawInput || "").slice(0, 120);
    add(desc, 50, 10);
    y -= 20;
  }

  // Table header
  y -= 5;
  lines.push(`0.5 w 50 ${y} m 545 ${y} l S`);
  y -= 16;
  add("Description", 50, 9, true);
  add("Qty", 320, 9, true);
  add("Unit Price", 370, 9, true);
  add("Amount", 470, 9, true);
  y -= 6;
  lines.push(`0.5 w 50 ${y} m 545 ${y} l S`);
  y -= 16;

  // Line items
  for (const item of job.lineItems) {
    if (y < 120) break;
    add(item.description.slice(0, 40), 50, 10);
    add(String(item.quantity), 320, 10);
    add(formatRand(item.unitPrice), 370, 10);
    add(formatRand(item.total), 470, 10);
    y -= 16;
  }

  y -= 8;
  lines.push(`0.5 w 50 ${y} m 545 ${y} l S`);
  y -= 18;

  // Totals
  add("Subtotal", 370, 10);
  add(formatRand(job.subtotal), 470, 10);
  y -= 14;
  if (job.vatRate > 0) {
    add(`VAT (${(job.vatRate * 100).toFixed(0)}%)`, 370, 10);
    add(formatRand(job.vatAmount), 470, 10);
    y -= 14;
  }
  add("TOTAL", 370, 12, true);
  add(formatRand(job.total), 470, 12, true);
  y -= 30;

  // Payment instructions
  lines.push(`0.5 w 50 ${y} m 545 ${y} l S`);
  y -= 18;
  add("PAYMENT INSTRUCTIONS", 50, 9, true);
  y -= 14;
  if (business.bankName) {
    add(`Bank: ${business.bankName}`, 50, 10);
    y -= 12;
  }
  if (business.bankAccount) {
    add(`Account: ${business.bankAccount}`, 50, 10);
    y -= 12;
  }
  if (business.bankBranch) {
    add(`Branch: ${business.bankBranch}`, 50, 10);
    y -= 12;
  }
  if (!business.bankName && !business.bankAccount) {
    add("Please contact us for payment details.", 50, 10);
    y -= 12;
  }
  add(`Reference: ${invoiceNumber}`, 50, 10);
  y -= 20;

  add("Thank you for your business.", 50, 10);
  y -= 14;
  add("Generated by InvoiceForge", 50, 8);

  return lines.join("\n");
}

export function generateInvoicePdf(
  business: Business,
  job: Job
): Uint8Array {
  const invoiceNumber = job.invoiceNumber || "DRAFT";
  const content = buildContentStream(business, job, invoiceNumber);

  const objects: string[] = [];

  objects.push("1 0 obj\n<< /Type /Catalog /Pages 2 0 R >>\nendobj\n");
  objects.push("2 0 obj\n<< /Type /Pages /Kids [3 0 R] /Count 1 >>\nendobj\n");
  objects.push(
    "3 0 obj\n<< /Type /Page /Parent 2 0 R /MediaBox [0 0 595 842] /Contents 4 0 R /Resources << /Font << /F1 5 0 R /F2 6 0 R >> >> >>\nendobj\n"
  );

  const stream = content;
  objects.push(
    `4 0 obj\n<< /Length ${stream.length} >>\nstream\n${stream}\nendstream\nendobj\n`
  );

  objects.push(
    "5 0 obj\n<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>\nendobj\n"
  );
  objects.push(
    "6 0 obj\n<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica-Bold >>\nendobj\n"
  );

  let pdf = "%PDF-1.4\n";
  const offsets: number[] = [0];

  for (const obj of objects) {
    offsets.push(pdf.length);
    pdf += obj;
  }

  const xrefPos = pdf.length;
  pdf += `xref\n0 ${objects.length + 1}\n`;
  pdf += "0000000000 65535 f \n";
  for (let i = 1; i <= objects.length; i++) {
    pdf += String(offsets[i]).padStart(10, "0") + " 00000 n \n";
  }
  pdf += `trailer\n<< /Size ${objects.length + 1} /Root 1 0 R >>\n`;
  pdf += `startxref\n${xrefPos}\n%%EOF\n`;

  return new TextEncoder().encode(pdf);
}
